version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_blog
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_HOST: 172.17.0.1
volumes:
  progresDB:
